---
driver:
  name: vagrant

provisioner:
  name: salt_solo
  formula: salt-api
  state_top:
    base:
      '*':
        - salt-api
        - salt-api.pepper

platforms:
  - name: ubuntu-12.04

suites:
  - name: default_stable
    provisioner:
    salt_version: 2015.5.3
    salt_install: apt
